### ISSUE TITLE
Implement desktop notifications

### ISSUE THREAD

**Issue by stone** [Lallassu/spinc#2]
It would be nice to have desktop notifications for private messages.
Ex using https://github.com/gen2brain/beeep 
#wishlist

**Comment by Lallassu** [comment]
I have investigated the use of sound/beep. But there are not good libraries for using sound devices for cross platform (that are not too large projects). Using system \a or \007 seems to be working just in some terminals (configuration dependent I guess).

But using some notification system would be better I guess. I will look into this!

**Comment by Lallassu** [comment]
Fixed in 055e2c77c845784a79d6457c914ea89e0be2fc11
